#!/usr/bin/env python3
"""
Compilation script for VVP Core Components

This script compiles the Cython extensions and sets up the core components
for maximum performance.
"""

import os
import sys
import subprocess
import logging
from pathlib import Path

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def check_dependencies():
    """Check if required dependencies are installed"""
    import platform
    
    required_packages = ['numpy', 'cython', 'psutil']
    optional_packages = []
    
    # Add uvloop for non-Windows systems
    if platform.system() != 'Windows':
        optional_packages.append('uvloop')
    
    missing_packages = []
    missing_optional = []
    
    # Check required packages
    for package in required_packages:
        try:
            __import__(package)
            logger.info(f"✓ {package} is installed")
        except ImportError:
            missing_packages.append(package)
            logger.error(f"✗ {package} is missing")
    
    # Check optional packages
    for package in optional_packages:
        try:
            __import__(package)
            logger.info(f"✓ {package} is installed (optional)")
        except ImportError:
            missing_optional.append(package)
            logger.warning(f"⚠ {package} is missing (optional, performance will be reduced)")
    
    if missing_packages:
        logger.error(f"Missing required packages: {missing_packages}")
        logger.info("Install with: pip install " + " ".join(missing_packages))
        return False
    
    if missing_optional:
        logger.info(f"Optional packages not installed: {missing_optional}")
        if platform.system() != 'Windows':
            logger.info("For better performance, install with: pip install " + " ".join(missing_optional))
    
    return True

def compile_cython_extensions():
    """Compile Cython extensions"""
    logger.info("Compiling Cython extensions...")
    
    # Change to core directory
    core_dir = Path(__file__).parent
    original_dir = os.getcwd()
    
    try:
        os.chdir(core_dir)
        
        # Run setup.py build_ext --inplace
        result = subprocess.run([
            sys.executable, 'setup.py', 'build_ext', '--inplace'
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            logger.info("✓ Cython compilation successful")
            logger.info(result.stdout)
            return True
        else:
            logger.error("✗ Cython compilation failed")
            logger.error(result.stderr)
            return False
            
    except Exception as e:
        logger.error(f"Error during compilation: {e}")
        return False
    finally:
        os.chdir(original_dir)

def run_performance_tests():
    """Run performance tests to verify everything works"""
    logger.info("Running performance tests...")
    
    try:
        # Test lock-free structures
        from lockfree_structures import LockFreePerformanceTester
        tester = LockFreePerformanceTester()
        results = tester.run_all_benchmarks()
        
        logger.info("Lock-free structures performance:")
        for structure, metrics in results.items():
            logger.info(f"  {structure}: {metrics['operations_per_second']:.0f} ops/sec")
        
        # Test fast order book (if compiled)
        try:
            from fast_orderbook import benchmark_order_book
            orderbook_results = benchmark_order_book(1000)
            logger.info(f"Order book performance: {orderbook_results['orders_per_second']:.0f} orders/sec")
            logger.info(f"Average latency: {orderbook_results['avg_latency_us']:.2f}μs")
        except ImportError:
            logger.warning("Fast order book not available (compilation may have failed)")
        
        return True
        
    except Exception as e:
        logger.error(f"Performance tests failed: {e}")
        return False

def cleanup_build_files():
    """Clean up build artifacts"""
    logger.info("Cleaning up build files...")
    
    core_dir = Path(__file__).parent
    
    # Remove build directories
    build_dirs = ['build', '__pycache__']
    for build_dir in build_dirs:
        build_path = core_dir / build_dir
        if build_path.exists():
            import shutil
            shutil.rmtree(build_path)
            logger.info(f"Removed {build_dir}")
    
    # Remove .c files generated by Cython
    for c_file in core_dir.glob('*.c'):
        c_file.unlink()
        logger.info(f"Removed {c_file.name}")

def main():
    """Main compilation process"""
    logger.info("Starting VVP Core Components compilation...")
    
    # Check dependencies
    if not check_dependencies():
        logger.error("Dependencies check failed. Please install missing packages.")
        return False
    
    # Compile Cython extensions
    if not compile_cython_extensions():
        logger.error("Compilation failed.")
        return False
    
    # Run performance tests
    if not run_performance_tests():
        logger.warning("Performance tests failed, but compilation succeeded.")
    
    logger.info("✓ VVP Core Components compilation complete!")
    logger.info("You can now import the high-performance components:")
    logger.info("  from backend.app.core import FastOrderBook, LockFreeSPSCQueue, AdvancedMemoryManager")
    
    return True

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)